pipeline {
    agent any

    stages {
        stage('docker build') {
            steps {
                script {
                    sh "docker build -f 02-primer-pipeline/Dockerfile -t saulmls/pipeline:3.0.-${BUILD_ID} 02-primer-pipeline"
                }
            }
        }
        
        stage('docker push') {
           steps {
               withCredentials([usernamePassword(credentialsId: 'dockerHub', passwordVariable: 'dockerHubPassword', usernameVariable: 'dockerHubUser')]) {
                   sh "docker login -u ${env.dockerHubUser} -p ${env.dockerHubPassword}"
                   sh 'docker push saulmls/pipeline:3.0.-${BUILD_ID}'
                }
            }
        }
        
        //stage('docker push') {
          //  steps {
            //    script {
                   // sh "docker push saulmls/pipeline:2.0.0-${BUILD_ID}"
              //  }
            //}
        //}
    }
}
